-- ─────────────────────────────────────────────────────────────────────
-- 0005_hr_announcements
--
-- HR monthly-announcement records. Each row is an editable announcement
-- generated by diffing two confirmed org_versions (before/after) plus
-- the employees master. The payload jsonb stores the editable sections
-- so manual edits don't get clobbered if the diff is re-run.
--
-- Section shape (informally typed by the app):
--   { hires:       [{ employee_number, full_name, department, position_title, hired_at, note? }, ...],
--     leaves:      [{ employee_number, full_name, department, position_title, left_at, note? }, ...],
--     divMoves:    [{ employee_number, full_name, fromDiv, toDiv, note? }, ...],
--     tmMoves:     [{ employee_number, full_name, fromTm,  toTm,  note? }, ...],
--     promotions:  [{ employee_number, full_name, fromRole, toRole, note? }, ...],
--     notes: string  -- free-form footer
--   }
-- ─────────────────────────────────────────────────────────────────────

create extension if not exists pgcrypto;

create table if not exists public.hr_announcements (
  id uuid primary key default gen_random_uuid(),
  period text not null,
  title text not null,
  version_a_id uuid references public.org_versions(id) on delete set null,
  version_b_id uuid references public.org_versions(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  created_by_email text,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists hr_announcements_period_idx
  on public.hr_announcements (period desc);

alter table public.hr_announcements enable row level security;

drop policy if exists "anon read hr_announcements" on public.hr_announcements;
create policy "anon read hr_announcements"
  on public.hr_announcements for select using (true);

drop policy if exists "anon write hr_announcements" on public.hr_announcements;
create policy "anon write hr_announcements"
  on public.hr_announcements for all using (true) with check (true);

-- Reuse the touch trigger from migration 0002 (function may not exist yet
-- on a fresh setup, so re-create just-in-case).
create or replace function public.touch_updated_at() returns trigger as $$
begin
  new.updated_at := now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists hr_announcements_touch_updated_at on public.hr_announcements;
create trigger hr_announcements_touch_updated_at
  before update on public.hr_announcements
  for each row execute function public.touch_updated_at();
